let schema = {
  required: [],
  type: "object",
  properties: {
    ros: {
      type: "array",
      default: [],
      items: {
        required: ["observation"],
        type: "object",
        properties: {
          observation: {
            templatable: true,
            type: "string",
            title: "Observation",
          },
          obsNotes: {
            type: "string",
            title: "Comment",
          },
        },
      },
    },
  },
};

let uiSchema = {
  ros: {
    classNames: "col-md-12",
    "ui:field": "collapsible",
    table: {
      tableCols: [
        {
          dataField: "observation",
          className: "col-md-4",
          columnClassName: "col-md-4",
          editColumnClassName: "col-md-4",
          field: "typeahead",
          uiSchema: {
            focusOnMount: true,
            typeahead: {
              placeholder: "Quick-pick ROS / Exam Observations",
              options: [
                "Anorexia",
                "Chills",
                "Fatigue",
                "Fevers",
                "Malaise",
                "Sweats",
                "Weight Loss",
                "Weight Gain",
                "Other",
                "Ear Pain or Discharge",
                "Decreased Hearing",
                "Nosebleeds",
                "Hoarseness",
                "Dysphagia",
                "Tinnitus",
                "Nasal Obstruction or Discharge",
                "Sore Throat",
                "Sinus Pains",
                "Blurring",
                "Diplopia",
                "Discharge",
                "Eye Pain",
                "Irritation",
                "Photophobia",
                "Vision Loss",
                "Floaters",
                "Cough",
                "Dyspnea",
                "Excessive Sputum",
                "Hemoptysis",
                "Wheezing",
                "Painful Breathing",
                "Sleep Disorder",
                "Snoring",
                "Chest Pains",
                "Palpitations",
                "Syncope",
                "Dyspnea on Exertion",
                "Orthopnea",
                "PND",
                "Peripheral Edema",
                "Tightness Chest",
                "Abdominal pain",
                "Constipation",
                "Hematochezia",
                "Jaundice",
                "Melena",
                "Nausea",
                "Vomiting",
                "Change in Bowel Habits",
                "Diarrhea",
                "Fatty Food Intolerance",
                "Heartburn",
                "Hemorrhoids",
                "Indigestion",
                "Loss of Appetite",
                "Blood in Stool",
                "Acid Reflux",
                "Decreased libido",
                "Dysuria",
                "Hematuria",
                "Hesitancy",
                "Impotence",
                "Incontinence",
                "Nocturia",
                "Genital Sores",
                "Arthritis",
                "Back Pain",
                "Joint Pain",
                "Joint Swelling",
                "Muscle Cramps",
                "Muscle Weakness",
                "Stiffness",
                "Leg Cramps",
                "Dryness",
                "Itching",
                "Rash",
                "Suspicious Lesions",
                "Ulcers",
                "Breast Lumps",
                "Breast Pain",
                "Nipple Discharge",
                "Paresthesias",
                "Seizures",
                "Transient paralysis",
                "Tremors",
                "Vertigo",
                "Weakness",
                "Headache",
                "Anxiety",
                "Depression",
                "Hallucinations",
                "Memory loss",
                "Mental disturbance",
                "Paranoia",
                "Suicidal ideation",
                "Panic Attacks",
                "Cold Intolerance",
                "Heat Intolerance",
                "Polydipsia",
                "Polyphagia",
                "Polyuria",
                "Weight Change",
                "Abnormal Sweat",
                "Excessive Hair",
                "Abnormal Bruising",
                "Bleeding",
                "Enlarged Lymph Nodes",
                "Anemia",
                "Bleeding Gums",
                "Lethargy",
                "Hay Fever",
                "HIV Exposure",
                "Persistent Infections",
                "Urticaria",
                "Post Nasal Drip",
                "Stuffy Nose",
                "Unusual Fatigue",
                "Frequent Colds",
              ],
              allowNew: true,
              minLength: 1,
            },
          },
        },
        {
          dataField: "obsNotes",
          className: "col-md-8",
          columnClassName: "col-md-8",
          editColumnClassName: "col-md-8",
        },
      ],
      focusOnAdd: 0,
      rightActions: [
        {
          action: "delete",
          className: "table-action",
          columnClassName: "table-action",
          editColumnClassName: "table-action",
          icon: "glyphicons glyphicons-remove-circle glyPhiconRedColor",
        },
      ],
    },
    nav: "intake",
    "ui:options": {
      label: false,
    },
    collapse: {
      field: "table",
      collapsed: false,
      icon: {
        add: "glyphicon glyphicon-plus-sign glyPhiconGreen",
      },
      addTo: "self",
    },
  },
};

export default { schema, uiSchema };
